function selectedLossLogs(){
  const logs=Array.isArray(state.usageLogs)?state.usageLogs:[],mode=$('#lossPeriodMode')?.value||'month',month=$('#lossReportMonth')?.value||'',year=String($('#lossReportYear')?.value||'');
  return logs.filter(log=>mode==='all'||(mode==='month'?log.date.startsWith(month):log.date.startsWith(year+'-')));
}
function lossAnalysis(){
  const logs=selectedLossLogs(),costs=state.productCosts||{},recyclingValues=state.recyclingValues||{};
  const rows=CIRCULAR_PRODUCTS.map(product=>{const entries=logs.filter(log=>log.productId===product.id),discarded=entries.reduce((sum,log)=>sum+Number(log.discarded||0),0),recycled=entries.reduce((sum,log)=>sum+Number(log.recycled||0),0),discardedKg=entries.reduce((sum,log)=>sum+Number(log.discardedKg||0),0),cost=Number(costs[product.id]||0),recyclingValue=Number(recyclingValues[product.id]||0),grossLoss=discarded*cost,savings=recycled*cost,profit=recycled*recyclingValue,totalBenefit=savings+profit;return {...product,cost,recyclingValue,discarded,recycled,discardedKg,grossLoss,savings,profit,totalBenefit,netLoss:Math.max(0,grossLoss-totalBenefit)}}).sort((a,b)=>b.grossLoss-a.grossLoss);
  const totals=rows.reduce((sum,row)=>({discarded:sum.discarded+row.discarded,recycled:sum.recycled+row.recycled,discardedKg:sum.discardedKg+row.discardedKg,grossLoss:sum.grossLoss+row.grossLoss,savings:sum.savings+row.savings,profit:sum.profit+row.profit,totalBenefit:sum.totalBenefit+row.totalBenefit,netLoss:sum.netLoss+row.netLoss}),{discarded:0,recycled:0,discardedKg:0,grossLoss:0,savings:0,profit:0,totalBenefit:0,netLoss:0});
  return {rows,totals};
}
function lossPriority(value,max){if(!value)return ['Sin pérdida','low'];const ratio=max?value/max:0;return ratio>=.65?['Alta','high']:ratio>=.25?['Media','medium']:['Baja','low']}
function renderLossAnalysis(){
  if(!$('#lossKpis'))return;const {rows,totals}=lossAnalysis(),recoveryRate=totals.grossLoss?Math.min(100,totals.totalBenefit/totals.grossLoss*100):0,top=[...rows].sort((a,b)=>b.grossLoss-a.grossLoss).find(row=>row.grossLoss>0),maxLoss=Math.max(...rows.map(row=>row.grossLoss),0);
  $('#lossKpis').innerHTML=[['Pérdida bruta',fmtClp(totals.grossLoss),`${totals.discarded} unidades desechadas`],['Ahorro al reciclar',fmtClp(totals.savings),`${totals.recycled} compras de reposición evitadas`],['Ganancia por reciclaje',fmtClp(totals.profit),'Ingreso por venta o retorno registrado'],['Beneficio total',fmtClp(totals.totalBenefit),'Ahorro más ganancia'],['Pérdida neta',fmtClp(totals.netLoss),`${fmtDiscardedKg(totals.discardedKg)} eliminados`],['Mayor impacto',top?top.name:'Sin pérdidas',top?`${fmtClp(top.grossLoss)} descartado`:'Registre costos y descartes']].map(([label,value,detail],index)=>`<article class="kpi"><div class="kpi-value">${escapeHtml(String(value))}</div><div class="kpi-label">${escapeHtml(label)}</div><div class="kpi-trend ${index===4&&totals.netLoss?'bad':''}">${escapeHtml(detail)}</div></article>`).join('');
  const groups=['Bandejas','Macetas'].map(group=>({group,loss:rows.filter(row=>row.group===group).reduce((sum,row)=>sum+row.grossLoss,0)})),groupMax=Math.max(...groups.map(group=>group.loss),0);
  $('#lossGroupComparison').innerHTML=groups.map(group=>`<div class="loss-group-row"><span>${group.group}</span><div class="loss-group-track"><span style="width:${groupMax?group.loss/groupMax*100:0}%"></span></div><strong>${fmtClp(group.loss)}</strong></div>`).join('');
  const status=$('#lossDecisionStatus'),recommendation=$('#lossRecommendation');
  if(!totals.grossLoss){status.className='pill warning';status.textContent='Sin datos';recommendation.innerHTML='<strong>Complete la información económica</strong><p>Ingrese costos, retornos y movimientos en Costos y circularidad para obtener una recomendación.</p><ul><li>Registrar precios de reposición y retorno del reciclaje.</li><li>Registrar unidades recicladas, desechadas y kilogramos eliminados.</li></ul>'}
  else if(recoveryRate>=80){status.className='pill success';status.textContent='Control favorable';recommendation.innerHTML=`<strong>Mantener el sistema de recuperación</strong><p>El ahorro y la ganancia del reciclaje compensan ${recoveryRate.toFixed(1)}% de la pérdida bruta registrada.</p><ul><li>El reciclaje evita compras por ${fmtClp(totals.savings)} y genera ingresos por ${fmtClp(totals.profit)}.</li><li>Mantener convenios y segregación actual.</li><li>Revisar ${escapeHtml(top?.name||'el producto principal')} para reducir la pérdida residual.</li></ul>`}
  else if(recoveryRate>=40){status.className='pill warning';status.textContent='Acción preventiva';recommendation.innerHTML=`<strong>Mejorar recuperación del producto prioritario</strong><p>La pérdida neta alcanza ${fmtClp(totals.netLoss)} y solo ${recoveryRate.toFixed(1)}% se compensa mediante reciclaje.</p><ul><li>Priorizar ${escapeHtml(top?.name||'el producto de mayor pérdida')}.</li><li>Definir meta mensual de reducción y revisar manipulación.</li><li>Evaluar reparación, reutilización o retorno al proveedor.</li></ul>`}
  else{status.className='pill danger';status.textContent='Intervención prioritaria';recommendation.innerHTML=`<strong>Reducir descarte antes de nuevas compras</strong><p>La recuperación es de solo ${recoveryRate.toFixed(1)}% y la pérdida neta asciende a ${fmtClp(totals.netLoss)}.</p><ul><li>Investigar la causa de descarte de ${escapeHtml(top?.name||'los productos')}.</li><li>Aplicar control de entrega y devolución por operario.</li><li>Comparar el costo de reposición con alternativas reutilizables.</li></ul>`}
  $('#lossProductsBody').innerHTML=rows.map(row=>{const [priority,level]=lossPriority(row.grossLoss,maxLoss);return `<tr><td><strong>${escapeHtml(row.name)}</strong></td><td>${row.group}</td><td>${fmtClp(row.cost)}</td><td>${row.discarded}</td><td>${fmtDiscardedKg(row.discardedKg)}</td><td class="money-negative">${fmtClp(row.grossLoss)}</td><td class="money-positive">${fmtClp(row.savings)}</td><td class="money-positive">${fmtClp(row.profit)}</td><td class="money-negative">${fmtClp(row.netLoss)}</td><td><span class="pill priority-${level}">${priority}</span></td></tr>`}).join('');
  $('#lossProductsFoot').innerHTML=`<tr><td colspan="3">TOTAL DEL PERÍODO</td><td>${totals.discarded}</td><td>${fmtDiscardedKg(totals.discardedKg)}</td><td class="money-negative">${fmtClp(totals.grossLoss)}</td><td class="money-positive">${fmtClp(totals.savings)}</td><td class="money-positive">${fmtClp(totals.profit)}</td><td class="money-negative">${fmtClp(totals.netLoss)}</td><td></td></tr>`;
}
const lossToday=new Date();$('#lossReportMonth').value=`${lossToday.getFullYear()}-${String(lossToday.getMonth()+1).padStart(2,'0')}`;$('#lossReportYear').value=lossToday.getFullYear();
$('#lossPeriodMode').addEventListener('change',event=>{$('#lossMonthField').classList.toggle('hidden',event.target.value!=='month');$('#lossYearField').classList.toggle('hidden',event.target.value!=='year');renderLossAnalysis()});$('#lossReportMonth').addEventListener('change',renderLossAnalysis);$('#lossReportYear').addEventListener('change',renderLossAnalysis);
$('#exportLossesCsv').addEventListener('click',()=>{const {rows}=lossAnalysis(),header=['Producto','Grupo','Costo unitario CLP','Retorno reciclaje unitario CLP','Desechadas','Recicladas','Kg eliminados','Pérdida bruta CLP','Ahorro CLP','Ganancia CLP','Beneficio total CLP','Pérdida neta CLP'],csv=[header.join(','),...rows.map(row=>[row.name,row.group,row.cost,row.recyclingValue,row.discarded,row.recycled,row.discardedKg,row.grossLoss,row.savings,row.profit,row.totalBenefit,row.netLoss].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','))].join('\n');download('analisis_perdidas_economicas.csv','\ufeff'+csv,'text/csv;charset=utf-8');toast('Análisis económico exportado.')});
const renderAllBeforeLosses=renderAll;renderAll=function(){renderAllBeforeLosses();renderLossAnalysis()};renderLossAnalysis();
